server:
  host: "127.0.0.1"
  port: 14348
  publicUrl: "https://mydomain"
uploadDir: "./uploads"
database:
  path: "data.db"
oauth:
  baseUrl: "https://mydomain"
  endpoint: "https://auth.mydomain"
  clientID: "..."
  clientSecret: "..."
  hash: [...]
sessionKey: [...]
